import type { Theme, GistData } from "@/types";

export const THEMES: Theme[] = [
  {
    id: "dark-luxury",
    name: "Dark Luxury",
    colors: {
      background: "#0a0806",
      surface: "#141210",
      primary: "#1a1612",
      accent: "#c9a84c",
      text: "#f5efe6",
      textMuted: "#8a7d6b",
      border: "#2a2420",
      gold: "#c9a84c",
    },
  },
  {
    id: "light-minimalist",
    name: "Light Minimalist",
    colors: {
      background: "#fafaf8",
      surface: "#ffffff",
      primary: "#f5f0e8",
      accent: "#8b6914",
      text: "#1a1410",
      textMuted: "#6b5e4e",
      border: "#e5ddd0",
      gold: "#8b6914",
    },
  },
  {
    id: "warm-pastel",
    name: "Warm Pastel",
    colors: {
      background: "#fdf6f0",
      surface: "#fff9f5",
      primary: "#f8ede3",
      accent: "#b07040",
      text: "#2d1f14",
      textMuted: "#7a5c44",
      border: "#e8d5c4",
      gold: "#c08050",
    },
  },
];

export const DEFAULT_DATA: GistData = {
  settings: {
    siteName: "MAISON OLFACT",
    logoUrl: "",
    faviconUrl: "",
    activeTheme: "dark-luxury",
    customColors: {},
    heroTitle: "The Art of Rare Scent",
    heroSubtitle: "Handcrafted perfumes inspired by the ancient routes of Arabia",
    heroImage: "",
    announcement: "Free shipping on orders over $150",
    currency: "USD",
    whatsapp: "",
    instagram: "",
    whatsappMessage: "Hello! I'd like to order:",
  },
  categories: [
    { id: "oriental", name: "Oriental", nameAr: "شرقي", icon: "✦" },
    { id: "woody", name: "Woody", nameAr: "خشبي", icon: "◈" },
    { id: "citrus", name: "Citrus", nameAr: "حمضيات", icon: "◉" },
    { id: "oud", name: "Oud", nameAr: "عود", icon: "◆" },
    { id: "floral", name: "Floral", nameAr: "زهري", icon: "✿" },
  ],
  products: [
    {
      id: "p1",
      name: "Noir de Sable",
      nameAr: "نوار دو سابل",
      tagline: "Black desert at midnight",
      description: "A deep, meditative journey through the heart of the Arabian desert. Smoky oud wrapped in amber resin and aged sandalwood.",
      category: "oud",
      images: ["https://images.unsplash.com/photo-1608528577891-eb055944f2e7?w=800"],
      variants: [
        { size: "30ml", price: 85, stock: 20, status: "available" },
        { size: "50ml", price: 130, stock: 8, status: "limited" },
        { size: "100ml", price: 220, stock: 0, status: "out_of_stock" },
      ],
      notes: {
        top: ["Saffron", "Black Pepper", "Bergamot"],
        heart: ["Oud", "Rose Absolute", "Patchouli"],
        base: ["Amber", "Sandalwood", "Musk"],
      },
      featured: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "p2",
      name: "Lumiere Doree",
      nameAr: "لوميير دوريه",
      tagline: "Dawn on gilded shores",
      description: "An opulent morning fragrance. Fresh citrus awakens into warm honey florals, resting on a bed of white musk and cedar.",
      category: "floral",
      images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800"],
      variants: [
        { size: "30ml", price: 75, stock: 15, status: "available" },
        { size: "50ml", price: 115, stock: 12, status: "available" },
        { size: "100ml", price: 195, stock: 5, status: "limited" },
      ],
      notes: {
        top: ["Neroli", "Lemon Zest", "Pink Pepper"],
        heart: ["Jasmine", "Honey", "Iris"],
        base: ["White Musk", "Cedar", "Vanilla"],
      },
      featured: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "p3",
      name: "Bois Sacre",
      nameAr: "بوا ساكريه",
      tagline: "Sacred forest ritual",
      description: "Enter a sacred grove. Ancient woods, incense smoke, and the mineral coldness of rain on stone.",
      category: "woody",
      images: ["https://images.unsplash.com/photo-1543884181-4c9c6f79b3ff?w=800"],
      variants: [
        { size: "50ml", price: 140, stock: 10, status: "available" },
        { size: "100ml", price: 240, stock: 6, status: "available" },
      ],
      notes: {
        top: ["Cardamom", "Vetiver", "Petrichor"],
        heart: ["Frankincense", "Cedarwood", "Labdanum"],
        base: ["Benzoin", "Oakmoss", "Castoreum"],
      },
      featured: false,
      createdAt: new Date().toISOString(),
    },
  ],
};
